# Generated by Django 3.2.6 on 2021-09-10 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listings_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='sold',
            field=models.BooleanField(default=False),
        ),
    ]
