# Generated by Django 3.2.6 on 2022-02-28 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_follow'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_from', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='like_from', to=settings.AUTH_USER_MODEL)),
                ('like_to', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='like_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
