# Generated by Django 3.2.6 on 2022-02-28 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='like_to',
        ),
        migrations.AddField(
            model_name='like',
            name='liked_post',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='liked_post', to='network.post'),
        ),
    ]
